projectwalktogether/src/common/layout.ts, projectwalktogether/src/pages/DetailPage.tsx
[feat]:디테일 페이지 작업중, 반응형 변수 사이즈 수정
=> [feat]:디테일 페이지 작업중, 반응형 변수 사이즈 수정

src/pages/MyPage/MyPage.tsx
=> [Test] : MyPage 잘 보내지는지 Test

src/pages/MyPage/MyPage.tsx
[feat] : MyPage 닉네임 기능 수정, 배너 아이콘 기능 추가
=> [feat] : MyPage 닉네임 기능 수정, 배너 아이콘 기능 추가

src/hooks/useDetectClose.ts, src/layout/Header.tsx
[fix] : src//hooks/useDetectClose 부분 타입오류 수정
=> [fix] : src//hooks/useDetectClose 부분 타입오류 수정

src/pages/MyPage/MyPage.tsx
MyPage 배너 아이콘 클릭시 새 창이 나와서 다시 한번 업로드 확인 기능 추가, 닉네임이랑 자기소개 글자수 제한 기능 추가"
=> MyPage 배너 아이콘 클릭시 새 창이 나와서 다시 한번 업로드 확인 기능 추가, 닉네임이랑 자기소개 글자수 제한 기능 추가"

src/components/CardSection/CardSection.tsx, src/pages/DetailPage/Comments/Comments.tsx, src/pages/DetailPage/DetailPage.tsx, src/pages/MainPage/FootOning.tsx, src/pages/MapPage/Map/map.tsx, src/pages/PostPage/Hooks/Calendar/AntCalendarDate.tsx, src/pages/PostPage/Hooks/Calendar/AntCalendarTime.tsx, src/pages/PostPage/InputInformation/InputInformation.tsx, src/pages/PostPage/Mainpost/Mainpost.tsx, src/pages/PostPage/PostPage.tsx
=> [fix]리코일 폴더주소 오류 수정

src/messagewindow/MessageWindow.tsx, src/pages/MyPage/MyPage2.tsx, src/pages/MyPage/likepage/MyPageLike.tsx, src/pages/MyPage/mypageWrite/MyPageWrite.tsx, src/pages/MyPage/tabbar/MypageTabbar.tsx, src/routes/router.tsx
=> "[feat] : 알림창 기능 추가"

src/App.tsx, src/messagewindow/MessageWindow.tsx, src/pages/DetailPage/Comments/Comments.tsx, src/pages/DetailPage/DropBox/DropBox.tsx
[feat] : 자기가 쓴 글 삭제버튼 누르면 알림창 나오는 기능 추가
=> [feat] : 자기가 쓴 글 삭제버튼 누르면 알림창 나오는 기능 추가

src/pages/ChatPage/ChattingBox/ChattingBox.tsx
=> [doc]pr 다시

src/components/CardSection/CardSection.tsx, src/messagewindow/MessageWindow.tsx, src/pages/ChangePassword/ChangePassword.tsx, src/pages/MyPage/likepage/MyPageLike.tsx, src/pages/MyPage/mypageProfile/MyPageProfile.tsx, src/pages/MyPage/mypageWrite/MyPageWrite.tsx, src/routes/router.tsx
[feat] : 좋아요 글 , 내가 쓴 글 불러오기 기능, 비밀번호 변경 기능 추가
=> [feat] : 좋아요 글 , 내가 쓴 글 불러오기 기능, 비밀번호 변경 기능 추가

src/components/CardSection/CardSection.style.tsx, src/components/CardSection/CardSection.tsx, src/pages/Category/Category.style.tsx, src/pages/MainPage/FootOning.tsx, src/pages/PostEditPage/PostEditPage.tsx, src/pages/PostPage/PostPage.tsx
[design] 카드 공통 컴포넌트 UI 완료 및 FootOning 공통 컴포넌트로 끼워놈
=> [design] 카드 공통 컴포넌트 UI 완료 및 FootOning 공통 컴포넌트로 끼워놈

src/pages/LoginPage/LoginPage.style.tsx, src/pages/LoginPage/LoginPage.tsx, src/pages/MainPage/MainPage.tsx, src/pages/MapPage/Map/map.tsx, src/pages/PostPage/InputInformation/InputInformation.style.tsx, src/pages/PostPage/PostPage.tsx, src/utils/CategorysList.ts
=> [doc]영상발표 이후 PR

src/pages/ChangePassword/ChangePassword.style.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.style.tsx, src/pages/ChatPage/ChattingList/ChattingList.style.tsx, src/pages/ChatPage/ChattingPage.tsx, src/pages/LoginPage/LoginPage.style.tsx, src/pages/SignUpPage/Agreement.style.tsx, src/pages/SignUpPage/SignUpPage.style.tsx, src/pages/SignUpPage/SignUpPage.tsx
[design]footer위치조정  login/ signup/ passwordchange/ chatting
=> [design]footer위치조정  login/ signup/ passwordchange/ chatting

src/components/HeaderAlarm/HeaderAlarm.tsx, src/layout/Header.style.tsx, src/layout/Header.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.tsx, src/pages/ChatPage/ChattingList/ChattingList.style.tsx, src/pages/PostPage/Hooks/Calendar/AntCalendarTime.tsx, src/pages/PostPage/Mainpost/Mainpost.style.tsx, src/pages/PostPage/PostPage.tsx, src/pages/PostPage/Postpage.style.tsx
채팅ui 수정 /커스텀얼럿/ 헤더알람 효과 없앰, x 버튼삭제/
=> [design] Error/mypagehandling

src/pages/ChangePassword/ChangePassword.tsx, src/pages/LoginPage/Findpassword.tsx
[feat] 뒤로가기 버튼 활성화 /ChnagePwd/FindFwd
=> [feat] 뒤로가기 버튼 활성화 /ChnagePwd/FindFwd

src/components/AuthStateListener/AuthStateListener.tsx, src/components/HeaderAlarm/HeaderAlarm.tsx, src/layout/Footer/Footer.tsx, src/layout/Header.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.style.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.tsx, src/pages/ChatPage/ChattingList/ChattingList.tsx
[doc]채팅박스 채팅사용법 추가/  cosole.log삭제/ 노션주소 변경
=> [doc]채팅박스 채팅사용법 추가/  cosole.log삭제/ 노션주소 변경

src/components/AuthStateListener/AuthStateListener.tsx, src/components/HeaderAlarm/HeaderAlarm.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.tsx, src/pages/LoginPage/Findpassword.tsx, src/pages/PostEditPage/Calendar/AntCalendarDateEdit.tsx, src/pages/PostEditPage/Calendar/AntCalendarTimeEdit.tsx, src/pages/PostEditPage/InputInformationEdit/InputInformationEdit.tsx, src/pages/PostEditPage/MainPostEdit/MainPostEdit.tsx, src/pages/PostPage/Hooks/Calendar/AntCalendarDate.tsx, src/pages/PostPage/Hooks/Calendar/AntCalendarTime.tsx, src/pages/PostPage/InputInformation/InputInformation.tsx, src/pages/PostPage/Mainpost/Mainpost.tsx, src/pages/PostPage/PostPage.tsx
[doc]console.log삭제 게시글페이지 헤더 채팅박스
=> [doc]console.log삭제 게시글페이지 헤더 채팅박스

src/pages/DetailPage/DetailPage.tsx, src/pages/PostPage/InputInformation/InputInformation.tsx
[doc]로그인 안 하고 함께걸을래요 버튼 누를시 alert창 삭제
=> [doc]로그인 안 하고 함께걸을래요 버튼 누를시 alert창 삭제

src/components/HeaderAlarm/HeaderAlarm.style.tsx, src/components/HeaderAlarm/HeaderAlarm.tsx, src/layout/Header.style.tsx, src/layout/Header.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.style.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.tsx, src/pages/ChatPage/ChattingList/ChattingList.style.tsx, src/pages/ChatPage/ChattingList/ChattingList.tsx, src/pages/ChatPage/ChattingPage.tsx
[doc] chating Box List 콘솔오류 수정 img, form태그 styled적용
=> [doc] chating Box List 콘솔오류 수정

src/pages/PostPage/PostPage.tsx
=> [doc] img태그변경 

src/components/AuthStateListener/AuthStateListener.tsx, src/components/HeaderAlarm/HeaderAlarm.tsx, src/components/ReviewModal/ReviewModal.tsx, src/pages/ChatPage/ChattingBox/ChattingBox.style.tsx, src/pages/ChatPage/ChattingList/ChattingList.tsx, src/pages/ChatPage/ChattingPage.tsx, src/pages/ChatPage/ReviewBox/ReviewBox.tsx, src/pages/DetailPage/DetailPage.tsx
리뷰저장기능 완성, 리뷰상대 클릭 시 채팅방이동, post의 ProceedState_Posting 업데이트, 리뷰방 이미지 변경
=> Feat/review 
